apiVersion: apps/v1
kind: Deployment
metadata:
  name: dailycode
  labels:
    app: dailycode
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dailycode
  template:
    metadata:
      labels:
        app: dailycode
    spec:
      containers:
        - name: dailycode
          image: 100xdevs/dailycode:603c372a0724df961c74cc469099db37577417db
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/apps/web/.env
              subPath: .env
            - name: secret
              mountPath: /usr/src/app/packages/db/.env
              subPath: .env
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dailycode-secret
                  key: DATABASE_URL
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: secret
          secret:
            secretName: dailycode-secret
            items:
              - key: .env
                path: .env
